"""Content for Shelly's in-depth guide pages (docs/guide/*.html) and the short
'What is this?' notes under each dashboard section. Edit here, then run
python scripts/build_guides.py."""

GUIDES = [
    {
        "slug": "kpis", "section": "s-kpi", "title": "This week: KPI tiles",
        "mini": "Six headline numbers for the last 7 days: sales, budget gap, gross margin, waste, delivery share and next week's forecast. Each is compared with last week, last year or a target.",
        "lead": "The six tiles answer one question: is the store on track this week? Each number has a comparison so it means something without extra context.",
        "glance": ["Sales (7 days) with week-on-week (WoW) and year-on-year (YoY) change",
                   "vs budget: budget = the same weeks last year × (1 + growth target, 4% by default)",
                   "Gross margin % against target (38% by default)",
                   "Waste + markdown as % of sales against a ≤3% target",
                   "Delivery share: Uber Eats + On-Demand as % of sales",
                   "Forecast for the next 7 days from the best model per category"],
        "how": ["Sales rows are cleaned: duplicates removed, refunds keyed as negative sales excluded, missing values rebuilt from units × price.",
                "The last 7 days are compared with the 7 days before, and with the same weekdays 52 weeks earlier (364 days, so Mondays line up with Mondays).",
                "Gross margin = sales − cost of goods. Waste value = units wasted × unit cost. Markdown value ≈ units marked down × price × 50%.",
                "Targets live in config.yaml, so a real store can set its own."],
        "method": [("WoW %", "(this week ÷ last week − 1) × 100"),
                   ("YoY %", "(this week ÷ same weekdays last year − 1) × 100"),
                   ("GM %", "(sales − COGS) ÷ sales × 100"),
                   ("Waste %", "(waste value + markdown value) ÷ sales × 100")],
        "read": ["Blue text means better than the comparison; red means worse.",
                 "Read the budget gap together with YoY: if YoY is negative too, the store is trading below last year, not just missing an ambitious budget.",
                 "A high gross margin with rising waste often means over-ordering on high-margin fresh lines."],
        "limits": ["Weekly numbers are noisy. One public holiday or promo week moves them a lot, so check the daily chart before reacting.",
                   "Markdown value is an estimate (50% of price) unless real markdown prices are supplied."],
        "ask": ["How did we trade this week?", "How are we tracking against budget?", "How's our margin?", "How's waste?"],
        "related": ["performance", "categories", "method"],
    },
    {
        "slug": "actions", "section": "s-act", "title": "Today's plan",
        "mini": "A ranked to-do list built from everything Shelly found. P1 = today, P2 = this week, P3 = next review. Each item gives the reason, the $ impact per week and an owner. Tick items off as you go.",
        "lead": "Findings are only useful if someone acts on them. Shelly's strategist turns model outputs into prioritised, costed and owned actions, the way a commercial manager would brief a store.",
        "glance": ["Priority order: compliance first, then P1 → P2 → P3, then largest $ impact",
                   "Each action has a 'why' built from the evidence, a weekly $ impact where it can be estimated, and an owner",
                   "Ticks are saved in your browser for this week only",
                   "'Ask why' explains any action in the chat"],
        "how": ["Rules map each finding type to an action: recall → pull and quarantine; channel outage → check the tablet at shift start; stock-out → emergency order; shrinkage → re-count and CCTV; count gain → check GR/DDN; waste blow-out → cut order ~30% and move markdowns earlier.",
                "KPI breaches add actions too: waste over target, margin under target, budget gap below −3%.",
                "The reorder list adds one P1 when lines are below lead-time cover. Rostering and range review add P3 items.",
                "Actions that meet the governance policy become decisions that wait for your confirmation (see Decisions)."],
        "method": [("$ / week", "Estimated weekly value at stake, e.g. lost sales from a stock-out = (usual units − actual) × price"),
                   ("Priority", "P1 = compliance or lost sales today · P2 = margin/shrink/waste this week · P3 = improvement")],
        "read": ["Start at the top and don't skip compliance items.",
                 "A $ figure of '–' means the value can't be estimated honestly (e.g. a GS1 barcode fix). It doesn't mean the item is unimportant."],
        "limits": ["$ impacts are estimates from the week's data, not audited figures.",
                   "The rules encode common convenience-store practice. Adjust them in strategist.py for a different format."],
        "ask": ["What should I do today?", "Why is the Uber Eats check a P1?"],
        "related": ["decisions", "exceptions", "operations"],
    },
    {
        "slug": "decisions", "section": "s-dec", "title": "Decisions: you stay in charge",
        "mini": "Major judgements (big $, compliance, price, range, credit, markdowns) are proposals, not actions. Confirm or reject each one. Shelly records who decided what and when, and learns from your answers.",
        "lead": "Shelly is designed as a decision-support system, not an autopilot. Anything that moves money or affects compliance waits for a human.",
        "glance": ["Governance policy in config.yaml: confirm anything over $250/week, plus always-confirm areas (recall, budget, range, replenishment, markdown, credit, customer terms, slotting, production, quality)",
                   "Every proposal has an id (D-1a2b3c4d), evidence, impact, confidence and a 7-day expiry",
                   "Answer in the web app (Confirm/Reject → Download → import), by CLI, or by typing 'confirm D-…' in the chat",
                   "The log is append-only: nothing is overwritten, so the full history can be audited"],
        "how": ["After each run, actions pass through the governance policy. Major ones are stored as 'pending'; minor ones are 'auto-approved' but still logged.",
                "Your answers are imported with python -m shelly decisions import shelly-decisions.json. The file is validated (schema, id format, size) before anything is applied.",
                "On the next run, the learning loop reads confirmed and rejected decisions and updates each rule's precision."],
        "method": [("Precision estimate", "Beta(1 + confirmed, 1 + rejected) → precision = α ÷ (α + β)"),
                   ("Tuning rule", "≥5 answers and precision < 40% → stricter threshold; > 85% → slightly earlier alerts, always within safe bounds")],
        "read": ["Rejecting a decision is useful feedback, not a failure. It teaches Shelly what counts as a false alarm in your store.",
                 "Add a short note when you reject (e.g. 'promo week'). Notes are kept in the audit trail."],
        "limits": ["The static website can't write back to GitHub, which is why answers are exported and imported. A future version can do this by email or through the Claude task."],
        "ask": ["What needs my confirmation?", "confirm D-1a2b3c4d", "What have you learned?"],
        "related": ["actions", "security", "method"],
    },
    {
        "slug": "performance", "section": "s-perf", "title": "Performance: daily sales, bridge and channels",
        "mini": "The daily sales line with next week's forecast (dashed), a bridge that splits the week-on-week change into volume, mix and price, and the delivery channels for 14 days so outages stand out.",
        "lead": "Three views that explain why the headline number moved.",
        "glance": ["Daily sales for 8 weeks plus the 7-day forecast (hover any day)",
                   "Sales bridge: last week → +volume → +mix → +price → this week",
                   "Delivery channels: Uber Eats and On-Demand per day for 14 days"],
        "how": ["The forecast is the sum of the best model per category (see Forecasts).",
                "The bridge uses per-SKU prices and units in both weeks.",
                "Channel lines come from the channel column in the sales export."],
        "method": [("Volume", "(units this week − units last week) × last week's average price"),
                   ("Mix", "(Σ mix share this week × last week's SKU price − last week's average price) × units this week"),
                   ("Price", "Σ (price this week − price last week) × units this week")],
        "read": ["More units but a negative mix means customers bought cheaper lines. Check promos and range.",
                 "A channel dropping to zero for a day or more is almost always an outage (tablet, app, account), not lost demand."],
        "limits": ["The bridge is a standard decomposition; small rounding differences are normal."],
        "ask": ["How did we trade this week?", "Is Uber Eats OK?", "Forecast for next week"],
        "related": ["models", "kpis"],
    },
    {
        "slug": "categories", "section": "s-cat", "title": "Categories: P&L and budget",
        "mini": "A profit and loss for each category (sales, margin, waste, contribution) plus the gap to budget. Tap a bar or row to ask Shelly about that category.",
        "lead": "Category management is where commercial decisions are made: range, space, price and promotion.",
        "glance": ["Sales, GM %, WoW, YoY, vs budget, waste and contribution per category",
                   "Diverging bar chart: behind budget (red) and ahead (blue)",
                   "Sortable table; tap a row to ask"],
        "how": ["Contribution = gross margin − waste − markdown.",
                "Budget = the same weeks last year × (1 + growth %)."],
        "method": [("Contribution", "GM − waste value − markdown value"), ("vs budget", "sales − budget")],
        "read": ["Look for categories that are behind budget and below last year. Those need a plan, not just a promo.",
                 "High GM % but low contribution means waste is eating the margin."],
        "limits": ["Budget is derived from last year. A real business would load its own budget file."],
        "ask": ["How's Food To Go?", "Which categories are behind budget?"],
        "related": ["kpis", "segments"],
    },
    {
        "slug": "exceptions", "section": "s-exc", "title": "Exceptions: what Shelly flagged",
        "mini": "Unusual events found by statistics, not guesswork: stock-outs, spikes, delivery outages, sustained declines (checked against last year for seasonality), waste blow-outs and SAP vs shelf count differences.",
        "lead": "Exception reporting means you only look at what's unusual. Each flag has the evidence and a $ impact.",
        "glance": ["Robust z-score against the same weekday over the previous 8 weeks",
                   "Sustained decline = last 14 days < 75% of the 8 weeks before. If it also fell last year, it's labelled seasonal",
                   "Shrinkage = physical count below SAP beyond tolerance; a count gain suggests a receiving or GR error"],
        "how": ["For each product and day, Shelly compares the day with the median of the same weekday in the last 8 weeks.",
                "It uses the median and MAD (median absolute deviation) instead of mean and standard deviation, so one odd day can't distort the baseline.",
                "Flags worth less than $40 are dropped to reduce noise. The thresholds tune themselves from your decisions."],
        "method": [("Robust z", "(x − median) ÷ (1.4826 × MAD)"), ("Default thresholds", "spike z ≥ 3 · stock-out z ≤ −3 · waste > 2× usual · decline < 75%")],
        "read": ["A drop plus plenty of stock on hand points to a shelf or display problem, not a stock-out.",
                 "A shrinkage flag marked 'repeat' is worth a CCTV review; 'first time' may be a counting error."],
        "limits": ["Daily data can't show time-of-day problems. Hourly POS data is on the roadmap."],
        "ask": ["Any problems this week?", "Any shrinkage?", "How's waste?"],
        "related": ["actions", "decisions"],
    },
    {
        "slug": "operations", "section": "s-ops", "title": "Operations: reorder list and roster",
        "mini": "Just-in-time reorder points with safety stock, capped at shelf life so fresh lines don't turn into waste. Recalled items are blocked. Roster hours come from forecast sales ÷ a productivity target.",
        "lead": "The two daily jobs that most affect sales and cost: what to order and who to roster.",
        "glance": ["Reorder point = demand over lead time + review period, plus safety stock",
                   "Order-up-to level is capped at average daily demand × shelf life",
                   "Status: 'Order now' (below lead-time cover), 'Order', 'OK' or 'Blocked, product recall'",
                   "Roster hours per day = forecast sales ÷ $ per labour hour, with a minimum per day"],
        "how": ["Demand μ and variability σ come from the last 28 days.",
                "On-hand stock is estimated as the last physical count minus sales since that count.",
                "Suggested order = order-up-to − on hand, only when on hand is below the reorder point."],
        "method": [("Safety stock", "z × σ × √(L + R), with z = 1.65 (≈95% service), L = lead time, R = review period"),
                   ("Reorder point", "μ × (L + R) + safety stock"),
                   ("Roster hours", "max(forecast sales ÷ sales-per-labour-hour, minimum hours)")],
        "read": ["Search the table by product or supplier to build each supplier's order.",
                 "If the wage % is high on quiet days, the minimum-hours rule is doing the work. That's a staffing policy question, not a forecast problem."],
        "limits": ["On-hand is an estimate between counts. Real SAP stock on hand would be more accurate.",
                   "Pack sizes and supplier minimums aren't applied yet."],
        "ask": ["What do I need to order?", "Should I order milk?", "How many hours should I roster?"],
        "related": ["actions", "models"],
    },
    {
        "slug": "whatif", "section": "s-whatif", "title": "What-if: price, waste and outage levers",
        "mini": "Move the sliders to see the weekly and yearly gross-margin effect of a price change (with elasticity), a waste reduction or fewer delivery outage days.",
        "lead": "A quick scenario model, the same maths as the Excel scenario sheet, for testing an idea before trying it.",
        "glance": ["Price change −10% to +10%", "Price elasticity −2.5 to −0.2 (default −1.2)", "Waste reduction 0–60%", "Outage days avoided per week"],
        "how": ["Volume change = price change × elasticity.", "New sales = sales × (1 + price change) × (1 + volume change).",
                "New GM % assumes unit costs stay the same.", "Uplift = new GM − base GM + waste saving + margin on recovered delivery sales."],
        "method": [("Elasticity", "% change in volume ÷ % change in price. −1.2 means a 1% price rise loses about 1.2% of volume")],
        "read": ["If the uplift turns negative as elasticity moves towards −2, the price rise only works for loyal or convenience-driven lines.",
                 "Waste reduction is usually the lowest-risk lever."],
        "limits": ["One elasticity for the whole store is a simplification. Categories differ a lot, so test on a few lines first."],
        "ask": ["What if we put prices up 3%?"],
        "related": ["kpis", "categories"],
    },
    {
        "slug": "packs", "section": "s-packs", "title": "Industry packs: beyond retail",
        "mini": "The same engine applied to consumer electronics (stock cover, aged stock, markdowns, price erosion, attach), wholesale (cost-to-serve, debtors, OTIF), warehousing (ABC-XYZ slotting, pick rates, capacity) and production (OEE, scrap, schedule adherence).",
        "lead": "Each pack is a set of skills with its own demo data, findings and decision proposals. Swap in real data through connectors.",
        "glance": ["Electronics: sell-through, weeks of cover, aged-stock ladder with a below-cost markdown check, ASP erosion, accessory attach rate",
                   "Wholesale: customer contribution after cost-to-serve, AR ageing and DSO, fill rate and OTIF",
                   "Warehousing: ABC (velocity) × XYZ (variability) slotting, lines per hour with coaching flags, weeks until 95% full",
                   "Production: OEE = availability × performance × quality, scrap cost, schedule adherence"],
        "how": ["Run a pack: python -m shelly pack electronics (or wholesale, warehousing, production).",
                "Findings become actions; major ones become decisions for confirmation.",
                "Full reports are in docs/example/pack_*.md."],
        "method": [("Weeks of cover", "on hand ÷ average weekly units (4 weeks)"), ("Cost-to-serve", "orders × cost per order ($18 default)"),
                   ("DSO", "receivables ÷ 90-day sales incl. GST × 90"), ("OEE", "(run time ÷ planned) × (units ÷ (run time × ideal rate)) × (good ÷ units)")],
        "read": ["In electronics, stock loses value every week it sits, so aged stock and weeks of cover matter more than turnover.",
                 "In wholesale, the biggest customers aren't always the most profitable once cost-to-serve is included.",
                 "In production, fix the biggest OEE loss first (availability, speed or quality)."],
        "limits": ["Pack demo data is synthetic. Cost assumptions (cost per order, unit cost) are placeholders to replace."],
        "ask": ["Tell me about warehousing", "Any electronics markdowns?", "What is our OEE?"],
        "related": ["decisions", "agents"],
    },
    {
        "slug": "segments", "section": "s-seg", "title": "Product segments (K-means)",
        "mini": "Products grouped by how they behave (speed, margin, volatility, waste, delivery share, promo response) using K-means, shown on 2 PCA axes. Stability scores show which groups are real and which are noise.",
        "lead": "Segmentation turns 50 SKUs into a handful of groups that each need a different strategy.",
        "glance": ["6 standardised features over 13 weeks", "k chosen by silhouette score (2–5)",
                   "Bootstrap Jaccard stability over 100 resamples: under 0.6 unstable, 0.6–0.75 a pattern, 0.75–0.85 stable, over 0.85 highly stable",
                   "Segments named by what makes them most distinctive"],
        "how": ["Features are standardised (z-scores) so no single unit dominates.", "K-means runs for k = 2…5 and the best silhouette is kept.",
                "PCA projects the 6 dimensions onto 2 for the chart only.", "The R validation script re-checks with the gap statistic and MANOVA."],
        "method": [("Silhouette", "(b − a) ÷ max(a, b), where a = mean distance within a cluster and b = to the nearest other cluster"),
                   ("Jaccard", "|A ∩ B| ÷ |A ∪ B| between original and resampled clusters")],
        "read": ["Treat unstable segments as hypotheses. Shelly says so rather than overselling.",
                 "Waste-exposed perishables → tighter ordering and earlier markdowns. Traffic drivers → never out of stock."],
        "limits": ["On demo data the silhouette is modest (~0.28) and the gap statistic prefers 2 clusters. That's reported honestly."],
        "ask": ["Tell me about the segments"],
        "related": ["categories", "models"],
    },
    {
        "slug": "models", "section": "s-mod", "title": "Forecasts: how good are they?",
        "mini": "Five models compete on each category: Naive, Seasonal Naive, Drift, SARIMA-X and XGBoost. Each is scored on the last 4 weeks (rolling origin) and the winner is used. A simple model is allowed to win.",
        "lead": "Forecast accuracy is measured, not assumed. The same approach as Pavi's MAB thesis, where seasonal naive beat XGBoost.",
        "glance": ["Rolling-origin backtest: 4 folds × 7 days", "Scored by WAPE (total absolute error ÷ total actual) and MAPE",
                   "Best model chosen per category", "Cross-checked independently in R"],
        "how": ["SARIMA-X: order (1,0,1)(1,1,1)[7] with a NZ public-holiday regressor, fitted on the last 364 days. If it becomes numerically unstable, it falls back to seasonal naive.",
                "XGBoost: one global model across categories with weekday, day-of-year, holiday and lagged features (lags ≥ 7, so a 7-day forecast needs no recursion).",
                "Baselines: last value, same day last week, and drift."],
        "method": [("WAPE", "Σ|actual − forecast| ÷ Σ actual × 100"), ("MAPE", "mean(|actual − forecast| ÷ actual) × 100 (skips zero days)")],
        "read": ["If the best model only beats seasonal naive by a point or two, the extra complexity isn't worth much.",
                 "A sudden jump in a model's error is flagged by the learning loop as possible drift."],
        "limits": ["No weather or promo calendar yet. Both are on the roadmap as model inputs."],
        "ask": ["Which model is most accurate?", "Forecast for next week"],
        "related": ["performance", "method"],
    },
    {
        "slug": "method", "section": "s-method", "title": "Method & data quality",
        "mini": "How Shelly works end to end (CRISP-DM) and how it checks the data first: duplicates, refunds keyed as sales, missing values, calendar gaps and unknown SKUs, summarised in a quality score.",
        "lead": "Every run follows the six CRISP-DM phases and leaves a validation report you can audit.",
        "glance": ["1 Business understanding: targets and thresholds in config.yaml",
                   "2 Data understanding: quality score out of 100", "3 Preparation: column mapping for real exports",
                   "4 Modelling: forecasts, exceptions, segments, reorder, roster", "5 Evaluation: backtests, stability checks, R cross-check",
                   "6 Deployment: this site, Excel, SQL, Power BI, Tableau, WhatsApp, run report"],
        "how": ["The quality score starts at 100 and loses points per issue (e.g. 0.5 per duplicate row, capped).",
                "The run report stores the SHA-256 of every input file, the config hash, and PASS/WARN/FAIL checks (freshness, beats the baseline, recalls blocked, P&L reconciles, cluster stability)."],
        "method": [("Validation checks", "Fresh ≤ 8 days · quality ≥ 80 · best WAPE ≤ seasonal naive · WAPE < 25% · recalls blocked · P&L reconciles · Jaccard ≥ 0.6")],
        "read": ["WARN means look before trusting a specific output. FAIL means don't act on that part."],
        "limits": ["The demo data is synthetic, generated to behave like a small Auckland convenience store."],
        "ask": ["How is the data quality?"],
        "related": ["security", "decisions"],
    },
    {
        "slug": "chat-voice", "section": "chat", "title": "Chat & voice",
        "mini": "Ask by typing, tapping a suggestion or speaking. Shelly checks whether the question fits its skills, answers from computed results, and can read answers aloud in your chosen region's voice.",
        "lead": "A conversational front door to the analytics, with voice in and out.",
        "glance": ["Built-in engine: instant, offline, never invents numbers",
                   "Optional Claude API or Ollama for more natural answers (facts only)",
                   "27 regions and languages for speech input and voice, e.g. NZ, AU, UK, US, India and South Africa English, Te reo Māori, Sinhala, Tamil, Hindi, Chinese, Japanese, Korean, Arabic and more",
                   "Speed and pitch controls; Test voice button; ▶ Briefing reads the week aloud"],
        "how": ["Speech input uses the browser's speech recognition in your chosen language.",
                "Voices are grouped: best match for your region, same language, then other English voices. If a voice isn't installed on your device, Shelly says so and uses the closest one.",
                "With the built-in engine, written answers are in English. With Claude or Ollama, answers are written in your chosen language."],
        "method": [("Skill tag", "Each answer shows which skill produced it, e.g. 'skill: retail.reorder'")],
        "read": ["Tap 🔈 under any answer to hear it; 🔊/🔇 turns automatic voice on or off."],
        "limits": ["Available voices depend on your phone or computer. Add more in its speech settings.",
                   "Voice input works in Chrome, Edge and Safari. Firefox doesn't support it yet."],
        "ask": ["What can you do?", "Play the briefing"],
        "related": ["agents", "security"],
    },
    {
        "slug": "agents", "section": "chat", "title": "Relevance check & connected agents",
        "mini": "Shelly tells you when a question is outside its skills (travel, email, writing, coding, investment advice, medical or legal questions, weather) and which kind of agent to connect in Settings. Nothing is sent to another agent unless you tap Send.",
        "lead": "A good agent knows its limits. Shelly answers what it's built for and routes the rest.",
        "glance": ["In scope: retail, electronics, wholesale, warehousing and production analytics",
                   "Out of scope: explains why and suggests the right agent type",
                   "Connected agents: Claude API, Ollama, or OpenJarvis / any OpenAI-compatible server on your computer",
                   "Hand-off needs your tap; only the question is sent, never store data"],
        "how": ["The router first checks for clear out-of-scope intents (e.g. 'book me a flight'), then tries every skill.",
                "In Python: python -m shelly ask \"…\" prints the matching skill or the advice."],
        "method": [("Skill match", "Share of the question's key words found in a skill's trigger phrases and description")],
        "read": ["Replies from connected agents are labelled 'not verified by Shelly'."],
        "limits": ["Keyword routing can miss unusual phrasing. Rephrase with a business term (sales, stock, order, margin…)."],
        "ask": ["Book me a flight to Colombo (see the advice)", "What do I need to order?"],
        "related": ["chat-voice", "security"],
    },
    {
        "slug": "td-report", "section": None, "title": "TD Report: daily Technology & Data newsletter",
        "mini": "", "lead": "Every morning at about 6:15am NZ time, Shelly researches, verifies and emails a 5-minute briefing, then saves a copy to Google Drive.",
        "glance": ["Sections: In 60 seconds · Retail & grocery NZ/AU · Consumer electronics · Wholesale, warehousing & production · AI, data & analytics · Markets (information only) · Roles that fit you",
                   "Every item needs 2+ independent sources (✓✓) or one official source (✓)",
                   "'So what' lines give practical relevance for a store, an analyst or a future business owner",
                   "Learns from your 👍/👎 or 'more on X' replies"],
        "how": ["Runs as a Claude scheduled task with standing pre-approval for a narrow set of actions: research, the Shelly Drive folder, reading your replies, and emailing only you.",
                "Keeps a Preferences & Feedback Log in Drive and applies changes once feedback is consistent."],
        "method": [("Verification", "Items with one unofficial source are dropped; numbers are never estimated")],
        "read": ["Reply to the email to tune tomorrow's edition."],
        "limits": ["Markets content is information, not advice.", "For fully unattended runs, turn on 'Automatically approve' in the task's settings."],
        "ask": [], "related": ["security"],
    },
    {
        "slug": "security", "section": None, "title": "Security & privacy",
        "mini": "", "lead": "Built as if it handled real store data: least privilege, human confirmation, audit trails and a locked-down web page.",
        "glance": ["Content Security Policy: own scripts only; network calls only to localhost and the Claude API",
                   "API keys are session-only unless you choose 'Remember'; one-click 'Clear all Shelly data'",
                   "Inputs capped and cleaned; LLM calls rate-limited; all output HTML-escaped",
                   "Python: SQL identifiers validated, raw SQL off by default, no path traversal, HTTPS-only connectors, decision imports schema-checked",
                   "Append-only decision log and SHA-256 hashed validation reports"],
        "how": ["See SECURITY.md in the repository for the full design and known limits.", "Tests in tests/test_security_router.py prove each control."],
        "method": [], "read": [],
        "limits": ["GitHub Pages can't send HTTP security headers, so the CSP is set by a meta tag (no frame-ancestors protection)."],
        "ask": [], "related": ["decisions", "agents"],
    },
]
