# Shelly Brain boot: the brain itself, sculpted in Blender and sampled into points of light.
# Two hemispheres (subdivided ellipsoids) get their folds from displacement textures (marble bands
# broken up by noise -> gyri and sulci), plus a ridged cerebellum and the brain stem. Points are then
# scattered over the surfaces with their normals and a "depth in the fold" value (sulci darker).
# Run headless:  python blender/shelly_brain_points.py   -> docs/brain/brain-points.js
import bpy, bmesh, math, random, os, base64, struct
from mathutils import Vector
from mathutils.bvhtree import BVHTree

random.seed(7)
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "docs", "brain", "brain-points.js")
for o in list(bpy.data.objects): bpy.data.objects.remove(o, do_unlink=True)

def ellipsoid(name, r, c, sub=6):
    bm = bmesh.new(); bmesh.ops.create_icosphere(bm, subdivisions=sub, radius=1)
    for v in bm.verts: v.co = Vector((v.co.x * r[0] + c[0], v.co.y * r[1] + c[1], v.co.z * r[2] + c[2]))
    me = bpy.data.meshes.new(name); bm.to_mesh(me); bm.free()
    o = bpy.data.objects.new(name, me); bpy.context.scene.collection.objects.link(o); return o

def displace(o, kind, scale, strength, **kw):
    tx = bpy.data.textures.new(o.name + kind, kind)
    for k, v in kw.items(): setattr(tx, k, v)
    tx.noise_scale = scale
    m = o.modifiers.new(kind, "DISPLACE"); m.texture = tx; m.strength = strength; m.texture_coords = "LOCAL"; m.mid_level = .5
    return m

# Blender axes: x = front/back, y = left/right, z = up
parts = []
for side in (-1, 1):   # hemispheres with the longitudinal fissure between them
    h = ellipsoid("hemi%d" % side, (2.15, 1.0, 1.45), (0, side * 1.06, .15), 6)
    displace(h, "MARBLE", .32, .16, marble_type="SHARPER", noise_basis="ORIGINAL_PERLIN", turbulence=6.0, noise_depth=3)
    displace(h, "CLOUDS", .5, .05)
    parts.append(("cere", h))
cb = ellipsoid("cerebellum", (.78, 1.05, .46), (1.35, 0, -1.02), 5)
displace(cb, "WOOD", .06, .05, wood_type="BANDNOISE", noise_basis_2="SIN", turbulence=1.0)
parts.append(("cereb", cb))
bpy.ops.mesh.primitive_cylinder_add(vertices=24, radius=.28, depth=1.4, location=(.42, 0, -1.5)); st = bpy.context.object; st.rotation_euler.y = .25
parts.append(("stem", st))

pts = []
dg = bpy.context.evaluated_depsgraph_get()
TARGET = {"cere": 9000, "cereb": 1700, "stem": 500}
for kind, o in parts:
    ev = o.evaluated_get(dg); me = bpy.data.meshes.new_from_object(ev); me.transform(o.matrix_world)
    bm = bmesh.new(); bm.from_mesh(me); bmesh.ops.triangulate(bm, faces=bm.faces[:]); bm.normal_update()
    faces = [f for f in bm.faces if not (kind == "cere" and abs(f.calc_center_median().y) < .12 and f.calc_center_median().z < .2)]
    areas = [f.calc_area() for f in faces]; tot = sum(areas); acc = []; s = 0
    for a in areas: s += a; acc.append(s)
    import bisect
    # radial distance of each vertex from the hemisphere centre -> fold depth (sulci are the low points)
    ctr = Vector((0, 0, .15))
    for n in range(TARGET[kind]):
        f = faces[bisect.bisect_left(acc, random.random() * tot)]
        a, b, c = [v.co for v in f.verts]; r1, r2 = random.random(), random.random()
        if r1 + r2 > 1: r1, r2 = 1 - r1, 1 - r2
        p = a + (b - a) * r1 + (c - a) * r2; nrm = f.normal
        depth = 0.5
        if kind == "cere":
            side = 1 if p.y > 0 else -1; cc = Vector((0, side * 1.06, .15)); q = p - cc
            e = math.sqrt((q.x / 2.15) ** 2 + (q.y / 1.0) ** 2 + (q.z / 1.45) ** 2); depth = max(0, min(1, (e - .9) / .2))
        pts.append((p.x, p.z, -p.y, nrm.x, nrm.z, -nrm.y, depth, {"cere": 0, "cereb": 1, "stem": 2}[kind]))   # web axes: y up
    bm.free()

P = struct.pack("<%dh" % (len(pts) * 3), *[max(-32767, min(32767, round(v * 8000))) for p in pts for v in p[:3]])
Nn = struct.pack("<%db" % (len(pts) * 3), *[max(-127, min(127, round(v * 127))) for p in pts for v in p[3:6]])
Dd = struct.pack("<%dB" % len(pts), *[min(255, round(p[6] * 200)) + 0 for p in pts])
Kk = struct.pack("<%dB" % len(pts), *[p[7] for p in pts])
with open(OUT, "w") as fh:
    fh.write("/* Generated by blender/shelly_brain_points.py - the Shelly Brain sculpted in Blender, sampled into points:\n"
             "   positions Int16 (x 1/8000 m), normals Int8, fold depth Uint8 (0 = deep in a sulcus), part Uint8 (0 cerebrum, 1 cerebellum, 2 stem). */\n")
    fh.write("export const BRAIN_POINTS = { n: %d, p: \"%s\", nrm: \"%s\", d: \"%s\", k: \"%s\" };\n" % (len(pts), base64.b64encode(P).decode(), base64.b64encode(Nn).decode(), base64.b64encode(Dd).decode(), base64.b64encode(Kk).decode()))
print("points", len(pts), "bytes", os.path.getsize(OUT))
